---
apiVersion: v1
kind: Pod
metadata:
  name: glpi
  labels:
    app: glpi
spec:
  containers:
    - name: front-end
      image: tiihxp/npglpidebian:2.0
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/var/www/html"
          name: task-pv-storage