machines = {
  "01" => {"memory" => "4096", "cpu" => "4", "ip" => "200", "image" => "generic/ubuntu2004"},
  "02" => {"memory" => "1024", "cpu" => "1", "ip" => "210", "image" => "generic/ubuntu2004"},
  "03" => {"memory" => "1024", "cpu" => "1", "ip" => "220", "image" => "generic/ubuntu2004"},
}

Vagrant.configure("2") do |config|
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.network "private_network", ip: "192.168.0.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
      end
    end
  end
end
