machines = {
  "Master" => {"memory" => "2048", "cpu" => "2", "ip" => "10", "image" => "generic/ubuntu1804"},
  "Worker1" => {"memory" => "2048", "cpu" => "2", "ip" => "20", "image" => "generic/ubuntu1804"},
  "Worker2" => {"memory" => "2048", "cpu" => "2", "ip" => "30", "image" => "generic/ubuntu1804"}
}

Vagrant.configure("2") do |config|
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.network "private_network", ip: "192.168.0.#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
      end
    end
  end
end